BANK_PATH = "random_bank.bin"
FLUSH_THRESHOLD = 32
CHUNK_SIZE = 32  
CONSUMER_SLEEP_TIME = 20
DEV_RANDOM_BYTE_RETURN = 32
COLLECT_ALL_RETURN_SIZE = 32
AUDIO_CHUNK_SIZE = 1024
AUDIO_SAMPLE_RATE = 16000
